' Scenario      : SIP.Test.SequenceDiagram.SeqScenario
' Instance pid  : #PID<0.332.0>
' Configuration (passwords masked):
'   username: "alice"
'   authusername: "alice"
'   domain: "example.com"
'   passwd: ****
'
@startuml
participant "alice" as local
participant "example.com" as peer
control "media server" as ms

note over local : initial_state
local -[#DarkOrange]> ms : connect
note over local : initial_state -> calling
local -> peer : INVITE
note over local : calling -> wait
note over local #LightGreen : succeeded: answered
@enduml
